/* USERS */
export const GET_USERS = "GET_USERS"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

/* USERS PROFILE */
export const GET_USER_PROFILE = "GET_USER_PROFILE"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL"

/**
 * add user
 */
export const ADD_NEW_USER = "ADD_NEW_USER"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAIL = "ADD_USER_FAIL"

/**
 * Edit user
 */
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

/**
 * Delete user
 */
export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const GET_ATTORNEYS = "GET_ATTORNEYS"

export const GET_ALL_ATTORNEYS = "GET_ALL_ATTORNEYS"
export const GET_ALL_ATTORNEYS_SUCCESS = "GET_ALL_ATTORNEYS_SUCCESS"
export const GET_ALL_ATTORNEYS_FAIL = "GET_ALL_ATTORNEYS_FAIL"

export const GET_ATTORNEYSCOUNT = "GET_ATTORNEYSCOUNT"
export const GET_ATTORNEYSCOUNT_SUCCESS = "GET_ATTORNEYSCOUNT_SUCCESS"
export const GET_ATTORNEYSCOUNT_FAIL = " GET_ATTORNEYSCOUNT_FAIL"
